export const STATUS_CODES = [
  "BERTUGAS",
  "MENUNGGU_JAM_MUAT",
  "DIJADWALKAN",
  "PENGIRIMAN_SELESAI",
  "NON_AKTIF",
];

export const driverNames = [
  "Mulyadi Saputra",
  "Nur Aini",
  "Oki Pratama",
  "Putri Ayu",
  "Qomaruddin Syah",
  "Rina Marlina",
  "Slamet Riyadi",
  "Tri Handoko",
  "Umi Kalsum",
  "Vicky Nugraha",
  "Wahyu Hidayah",
  "Xavier Nugroho",
  "Yani Pratiwi",
  "Zulfikar Ramadhan",
  "Arif Wibowo",
  "Bella Anjani",
  "Cahyo Nugroho",
  "Dian Permata",
  "Endang Sri",
  "Farhan Firmansyah",
  "Gita Larasati",
  "Hendra Saputra",
  "Indah Purnama",
  "Johan Prasetya",
  "Kiki Amalia",
  "Linda Kurnia",
  "Mahendra Putra",
  "Nadia Salsabila",
  "Omar Satria",
  "Prasetyo Adi",
  "Rudi Hartono",
  "Sari Melati",
  "Taufik Ismail",
  "Ujang Koswara",
  "Vina Maharani",
  "Wulan Anggraini",
  "Yusuf Maulana",
  "Zahra Fitriana",
  "Bagus Priyanto",
  "Citra Anindya",
  "Dwi Saputro",
  "Erlangga Putra",
  "Fauzi Rahman",
  "Galuh Paramitha",
  "Hanif Setiawan",
  "Ilham Fauzan",
  "Jasmin Safira",
  "Kusnadi Hermawan",
  "Lestari Puspita",
];

export const truckTypes = [
  "Colt Diesel Engkel - Box",
  "Tronton Wing Box",
  "Fuso Box",
  "Pickup Bak",
  "Container 20ft",
  "Trailer Flatbed",
  "Colt Diesel Engkel - Bak",
  "Colt Diesel Double - Box",
  "Colt Diesel Double - Bak",
  "Tronton Bak Terbuka",
  "Fuso Wing Box",
  "Fuso Bak Terbuka",
  "Pickup Box",
  "Container 40ft",
  "Trailer Lowbed",
  "Trailer Box",
  "Engkel Box Pendingin",
  "Double Box Pendingin",
  "Tronton Tangki",
  "Trailer Tangki",
];

export const locations = [
  "Rest Area KM 50",
  "Garasi Pool Kendaraan",
  "Pelabuhan Tanjung Priok",
  "Gudang Utama, Jakarta Utara",
  "Pabrik Tekstil, Bandung Barat",
  "Depo Kontainer, Tanjung Perak",
  "Pusat Distribusi, Banjarmasin",
  "Kawasan Industri Cikarang",
  "Gudang Logistik, Semarang",
  "Pelabuhan Soekarno-Hatta, Makassar",
  "Gudang Pendingin, Surabaya",
  "Pabrik Makanan, Bogor",
  "Pelabuhan Panjang, Lampung",
  "Depo Peti Kemas, Belawan",
  "Kawasan Industri Jababeka",
  "Gudang Ekspedisi, Medan",
  "Pusat Pergudangan, Denpasar",
  "Terminal Kargo, Balikpapan",
  "Rest Area KM 102",
  "Pabrik Semen, Gresik",
  "Pelabuhan Bitung, Manado",
  "Gudang Farmasi, Bekasi",
  "Depo Logistik, Palembang",
  "Kawasan Industri Sidoarjo",
  "Pusat Distribusi, Pontianak",
  "Pelabuhan Tenau, Kupang",
  "Gudang Umum, Yogyakarta",
  "Pabrik Kertas, Karawang",
  "Rest Area KM 72",
  "Depo Truk, Tangerang",
  "Gudang Pakaian, Cirebon",
  "Pelabuhan Sampit, Kalimantan Tengah",
  "Kawasan Industri Batam",
  "Gudang Bahan Kimia, Cilacap",
  "Pusat Logistik, Banda Aceh",
  "Rest Area KM 200",
  "Pelabuhan Jayapura",
  "Pabrik Baja, Cilegon",
  "Gudang Kayu, Pekanbaru",
  "Depo Minyak, Balongan",
  "Kawasan Industri Morowali",
  "Gudang Beras, Indramayu",
  "Pelabuhan Ketapang, Banyuwangi",
  "Terminal Petikemas, Surabaya",
  "Pabrik Minuman, Sukabumi",
  "Rest Area KM 125",
  "Gudang Elektronik, Depok",
  "Pelabuhan Kendari",
  "Kawasan Pergudangan, Samarinda",
  "Pabrik Ban, Majalengka",
  "Gudang Material, Purwokerto",
  "Depo Kontainer, Sorong",
  "Pusat Distribusi, Ternate",
  "Pelabuhan Fakfak",
  "Rest Area KM 88",
  "Gudang Otomotif, Malang",
  "Kawasan Industri Pulogadung",
  "Pabrik Plastik, Serang",
  "Gudang Sembako, Garut",
  "Depo Logistik, Mataram",
  "Pelabuhan Ambon",
  "Pusat Pergudangan, Padang",
  "Gudang Besi, Tasikmalaya",
  "Rest Area KM 150",
  "Pelabuhan Parepare",
  "Pabrik Keramik, Klaten",
  "Gudang Kaca, Kendal",
  "Depo Truk, Banjarbaru",
  "Kawasan Industri Kendal",
  "Pusat Logistik, Manokwari",
  "Pelabuhan Bau-Bau",
  "Rest Area KM 230",
  "Gudang Kain, Jepara",
  "Pabrik Obat, Solo",
  "Gudang Peralatan, Tegal",
  "Pelabuhan Lembar, Lombok",
  "Kawasan Industri Pasuruan",
  "Depo Peti Kemas, Dumai",
  "Pusat Distribusi, Bontang",
  "Rest Area KM 310",
  "Pelabuhan Bima",
  "Gudang Bumbu, Blitar",
  "Pabrik Susu, Boyolali",
  "Gudang Perikanan, Bitung",
  "Depo Kontainer, Tarakan",
  "Pelabuhan Singkil",
  "Kawasan Industri Balikpapan",
  "Pusat Pergudangan, Probolinggo",
  "Gudang Alat Berat, Kudus",
  "Rest Area KM 400",
  "Pelabuhan Tual",
  "Pabrik Furniture, Madiun",
  "Gudang Perkebunan, Lubuklinggau",
  "Depo Logistik, Pangkalan Bun",
  "Pelabuhan Saumlaki",
  "Kawasan Industri Gowa",
  "Gudang Kopi, Aceh Tengah",
  "Rest Area KM 450",
];
