export const baseTransporters = [
  {
    id: "TPT_001",
    companyName: "PT. Logistik Cepat",
    logo: "/img/seller-logo.png",
    rating: 5.0,
    orderCount: 320,
  },
  {
    id: "TPT_002",
    companyName: "PT Global Express Logistics",
    logo: "/img/seller-logo.png",
    rating: 5.0,
    orderCount: 280,
  },
  {
    id: "TPT_003",
    companyName: "PT Nusantara Cargo Solutions",
    logo: "/img/seller-logo.png",
    rating: 4.9,
    orderCount: 300,
  },
  {
    id: "TPT_004",
    companyName: "PT Swift Transport Indonesia",
    logo: "/img/seller-logo.png",
    rating: 4.9,
    orderCount: 250,
  },
  {
    id: "TPT_005",
    companyName: "PT. Solusi Distribusi",
    logo: "/img/seller-logo.png",
    rating: 4.9,
    orderCount: 290,
  },
  {
    id: "TPT_006",
    companyName: "PT Mega Freight Services",
    logo: "/img/seller-logo.png",
    rating: 4.8,
    orderCount: 260,
  },
  {
    id: "TPT_007",
    companyName: "Global Freightindo",
    logo: "/img/seller-logo.png",
    rating: 4.8,
    orderCount: 220,
  },
  {
    id: "TPT_008",
    companyName: "PT Indo Pacific Transport",
    logo: "/img/seller-logo.png",
    rating: 4.8,
    orderCount: 270,
  },
  {
    id: "TPT_009",
    companyName: "Jasa Kirim Kilat",
    logo: "/img/seller-logo.png",
    rating: 4.7,
    orderCount: 240,
  },
  {
    id: "TPT_010",
    companyName: "CV Jaya Mandiri Logistics",
    logo: "/img/seller-logo.png",
    rating: 4.6,
    orderCount: 230,
  },
  {
    id: "TPT_011",
    companyName: "PT. Siba Surya",
    logo: "/img/seller-logo.png",
    rating: 4.9,
    orderCount: 310,
  },
];

export const successShell = {
  Message: { Code: 200, Text: "Transporter ratings retrieved successfully" },
  Data: {},
  Type: "TRANSPORTER_RATINGS_LIST",
};
