export const successResponse = {
  Message: {
    Code: 200,
    Text: "Data shipper berhasil diambil",
  },
  Data: {
    shippers: [
      {
        id: "shipper-1",
        fullName: "John Customer",
        userType: "USER_01",
        email: "john.customer@ptmaju.com",
        whatsappNumber: "+628111000001",
        companyName: "PT Maju Jaya",
        companyAddress: "Jl. Maju No.1",
        activeOrders: 12,
        completedOrders: 120,
        contacts: [
          {
            name: "Budi",
            position: "PIC",
            phoneNumber: "+628111000001",
            Level: 1,
          },
        ],
        emergency: {
          name: "Budi",
          position: "Admin",
          phoneNumber: "+628111000001",
        },
        picPhone: "0811000001",
        status: "Active",
        registeredDate: "2024-01-10",
      },
      {
        id: "shipper-2",
        fullName: "Siti Rahma",
        userType: "USER_02",
        email: "siti.rahma@sentosa.co.id",
        whatsappNumber: "+628111000002",
        companyName: "CV Sentosa Abadi",
        companyAddress: "Jl. Sentosa No.5",
        activeOrders: 3,
        completedOrders: 34,
        contacts: [
          {
            name: "Siti",
            position: "Manager",
            phoneNumber: "+628111000002",
            Level: 1,
          },
        ],
        emergency: {
          name: "Siti",
          position: "Manager",
          phoneNumber: "+628111000002",
        },
        picPhone: "0811000002",
        status: "Active",
        registeredDate: "2024-02-01",
      },
      {
        id: "shipper-3",
        fullName: "Agus Salim",
        userType: "USER_01",
        email: "agus.salim@berkah.co",
        whatsappNumber: "+628111000003",
        companyName: "UD Berkah Mandiri",
        companyAddress: "Komplek Berkah 3",
        activeOrders: 0,
        completedOrders: 7,
        contacts: [
          {
            name: "Agus",
            position: "Owner",
            phoneNumber: "+628111000003",
            Level: 1,
          },
        ],
        emergency: {
          name: "Agus",
          position: "Owner",
          phoneNumber: "+628111000003",
        },
        picPhone: "0811000003",
        status: "Inactive",
        registeredDate: "2023-12-20",
      },
      // more varied mock shippers
      {
        id: "shipper-4",
        fullName: "PT Logistik Prima",
        userType: "USER_02",
        email: "contact@logistikprima.com",
        whatsappNumber: "+628111000004",
        companyName: "PT Logistik Prima",
        companyAddress: "Jl. Prima 10",
        activeOrders: 7,
        completedOrders: 89,
        contacts: [
          {
            name: "Lina",
            position: "PIC",
            phoneNumber: "+628111000004",
            Level: 1,
          },
        ],
        emergency: {
          name: "Lina",
          position: "PIC",
          phoneNumber: "+628111000004",
        },
        picPhone: "0811000004",
        status: "Active",
        registeredDate: "2024-03-12",
      },
      {
        id: "shipper-5",
        fullName: "PT Toko Jaya",
        userType: "USER_02",
        email: "hello@tokojaya.id",
        whatsappNumber: "+628111000005",
        companyName: "PT Toko Jaya",
        companyAddress: "Jl. Toko 7",
        activeOrders: 20,
        completedOrders: 200,
        contacts: [
          {
            name: "Anton",
            position: "Manager",
            phoneNumber: "+628111000005",
            Level: 1,
          },
        ],
        emergency: {
          name: "Anton",
          position: "Manager",
          phoneNumber: "+628111000005",
        },
        picPhone: "0811000005",
        status: "Active",
        registeredDate: "2023-11-05",
      },
      {
        id: "shipper-6",
        fullName: "CV Mitra Selalu",
        userType: "USER_02",
        email: "info@mitraselalu.co.id",
        whatsappNumber: "+628111000006",
        companyName: "CV Mitra Selalu",
        companyAddress: "Jl. Mitra 2",
        activeOrders: 1,
        completedOrders: 5,
        contacts: [
          {
            name: "Rini",
            position: "Supervisor",
            phoneNumber: "+628111000006",
            Level: 1,
          },
        ],
        emergency: {
          name: "Rini",
          position: "Supervisor",
          phoneNumber: "+628111000006",
        },
        picPhone: "0811000006",
        status: "Inactive",
        registeredDate: "2024-01-20",
      },
      {
        id: "shipper-7",
        fullName: "PT Sumber Karya",
        userType: "USER_02",
        email: "sales@sumberkarya.co.id",
        whatsappNumber: "+628111000007",
        companyName: "PT Sumber Karya",
        companyAddress: "Jl. Sumber 33",
        activeOrders: 9,
        completedOrders: 54,
        contacts: [
          {
            name: "Dewi",
            position: "PIC",
            phoneNumber: "+628111000007",
            Level: 1,
          },
        ],
        emergency: {
          name: "Dewi",
          position: "PIC",
          phoneNumber: "+628111000007",
        },
        picPhone: "0811000007",
        status: "Active",
        registeredDate: "2024-04-02",
      },
      {
        id: "shipper-8",
        fullName: "PT Rapid Express",
        userType: "USER_02",
        email: "support@rapidexpress.com",
        whatsappNumber: "+628111000008",
        companyName: "PT Rapid Express",
        companyAddress: "Jl. Ekspedisi 8",
        activeOrders: 0,
        completedOrders: 2,
        contacts: [
          {
            name: "Eko",
            position: "Coordinator",
            phoneNumber: "+628111000008",
            Level: 1,
          },
        ],
        emergency: {
          name: "Eko",
          position: "Coordinator",
          phoneNumber: "+628111000008",
        },
        picPhone: "0811000008",
        status: "Inactive",
        registeredDate: "2023-10-21",
      },
      {
        id: "shipper-9",
        fullName: "CV Prima Logistik",
        userType: "USER_02",
        email: "contact@primalogistik.id",
        whatsappNumber: "+628111000009",
        companyName: "CV Prima Logistik",
        companyAddress: "Jl. Prima 9",
        activeOrders: 4,
        completedOrders: 40,
        contacts: [
          {
            name: "Fajar",
            position: "PIC",
            phoneNumber: "+628111000009",
            Level: 1,
          },
        ],
        emergency: {
          name: "Fajar",
          position: "PIC",
          phoneNumber: "+628111000009",
        },
        picPhone: "0811000009",
        status: "Active",
        registeredDate: "2024-05-11",
      },
      {
        id: "shipper-10",
        fullName: "Toko Sumber",
        userType: "USER_02",
        email: "owner@tokosumber.com",
        whatsappNumber: "+628111000010",
        companyName: "Toko Sumber",
        companyAddress: "Jl. Sumber 10",
        activeOrders: 15,
        completedOrders: 150,
        contacts: [
          {
            name: "Gita",
            position: "Owner",
            phoneNumber: "+628111000010",
            Level: 1,
          },
        ],
        emergency: {
          name: "Gita",
          position: "Owner",
          phoneNumber: "+628111000010",
        },
        picPhone: "0811000010",
        status: "Active",
        registeredDate: "2024-06-01",
      },
      // add a few more to allow multiple pages
      {
        id: "shipper-11",
        fullName: "CV Cahaya",
        userType: "USER_02",
        email: "info@cahayacv.id",
        whatsappNumber: "+628111000011",
        companyName: "CV Cahaya",
        companyAddress: "Jl. Cahaya 11",
        activeOrders: 2,
        completedOrders: 20,
        contacts: [
          {
            name: "Hendra",
            position: "PIC",
            phoneNumber: "+628111000011",
            Level: 1,
          },
        ],
        emergency: {
          name: "Hendra",
          position: "PIC",
          phoneNumber: "+628111000011",
        },
        picPhone: "0811000011",
        status: "Active",
        registeredDate: "2024-06-10",
      },
      {
        id: "shipper-12",
        fullName: "PT Sinergi",
        userType: "USER_02",
        email: "contact@sinergi.co.id",
        whatsappNumber: "+628111000012",
        companyName: "PT Sinergi",
        companyAddress: "Jl. Sinergi 12",
        activeOrders: 6,
        completedOrders: 60,
        contacts: [
          {
            name: "Rico",
            position: "Manager",
            phoneNumber: "+628111000012",
            Level: 1,
          },
        ],
        emergency: {
          name: "Rico",
          position: "Manager",
          phoneNumber: "+628111000012",
        },
        picPhone: "0811000012",
        status: "Active",
        registeredDate: "2023-09-12",
      },
      {
        id: "shipper-13",
        fullName: "UD Makmur",
        userType: "USER_01",
        email: "ud.makmur@example.com",
        whatsappNumber: "+628111000013",
        companyName: "UD Makmur",
        companyAddress: "Jl. Makmur 13",
        activeOrders: 0,
        completedOrders: 3,
        contacts: [
          {
            name: "Slamet",
            position: "Owner",
            phoneNumber: "+628111000013",
            Level: 1,
          },
        ],
        emergency: {
          name: "Slamet",
          position: "Owner",
          phoneNumber: "+628111000013",
        },
        picPhone: "0811000013",
        status: "Inactive",
        registeredDate: "2023-08-01",
      },
      {
        id: "shipper-14",
        fullName: "PT Bukit",
        userType: "USER_02",
        email: "hello@ptbukit.com",
        whatsappNumber: "+628111000014",
        companyName: "PT Bukit",
        companyAddress: "Jl. Bukit 14",
        activeOrders: 11,
        completedOrders: 110,
        contacts: [
          {
            name: "Nina",
            position: "PIC",
            phoneNumber: "+628111000014",
            Level: 1,
          },
        ],
        emergency: {
          name: "Nina",
          position: "PIC",
          phoneNumber: "+628111000014",
        },
        picPhone: "0811000014",
        status: "Active",
        registeredDate: "2024-02-14",
      },
      {
        id: "shipper-15",
        fullName: "CV Alami",
        userType: "USER_02",
        email: "sales@alamicorp.id",
        whatsappNumber: "+628111000015",
        companyName: "CV Alami",
        companyAddress: "Jl. Alami 15",
        activeOrders: 8,
        completedOrders: 88,
        contacts: [
          {
            name: "Rosa",
            position: "Supervisor",
            phoneNumber: "+628111000015",
            Level: 1,
          },
        ],
        emergency: {
          name: "Rosa",
          position: "Supervisor",
          phoneNumber: "+628111000015",
        },
        picPhone: "0811000015",
        status: "Active",
        registeredDate: "2024-03-01",
      },
    ],
    pagination: {
      currentPage: 1,
      totalPages: 2,
      totalItems: 15,
      itemsPerPage: 10,
    },
  },
  Type: "GET_SHIPPERS_LIST",
};

export const errorResponse = {
  Message: {
    Code: 400,
    Text: "Bad Request",
  },
  Data: {
    errors: [
      {
        field: "general",
        message: "Terjadi kesalahan pada input",
      },
    ],
  },
  Type: "GET_SHIPPERS_LIST_ERROR",
};

export const serverErrorResponse = {
  Message: {
    Code: 500,
    Text: "Internal Server Error",
  },
  Data: {
    errors: [
      {
        field: "general",
        message: "Terjadi kesalahan pada sistem kami",
      },
    ],
  },
  Type: "INTERNAL_SERVER_ERROR",
};
