export const FleetSearchStatusEnum = {
  SEARCHING: "SEARCHING",
  FOUND: "FOUND",
  NOT_FOUND: "NOT_FOUND",
};

export const LocationTypeEnum = {
  PICKUP: "PICKUP",
  DROPOFF: "DROPOFF",
};

export const OrderStatusEnum = {
  SEARCHING_FLEET: "SEARCHING_FLEET",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CONFIRMED: "CONFIRMED",
  LOADING_PROCESS: "LOADING_PROCESS",
  UNLOADING_PROCESS: "UNLOADING_PROCESS",
  DOCUMENT_PREPARATION: "DOCUMENT_PREPARATION",
  DOCUMENT_SHIPPING: "DOCUMENT_SHIPPING",
  COMPLETED: "COMPLETED",
};

export const PaymentStatusEnum = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
};
