export const filterOptionsData = {
  transporters: [
    { id: "transporter-001", label: "PT Siba Surya" },
    { id: "transporter-002", label: "PT Abadi Transport" },
    { id: "transporter-003", label: "PT Bintang Jaya Transport" },
    { id: "transporter-004", label: "PT Citra Lestari Transport" },
    { id: "transporter-005", label: "PT Duta Angkasa Transport" },
  ],
  shippers: [
    { id: "shipper-001", label: "Agam Tunggal Jaya" },
    { id: "shipper-002", label: "Arjuna Logistik" },
    { id: "shipper-003", label: "Bintang Ekspres" },
    { id: "shipper-004", label: "Cahaya Transportasi" },
    { id: "shipper-005", label: "Dharma Pengiriman" },
  ],
  statuses: [
    { id: "MENUNGGU_KONFIRMASI", label: "Menunggu Konfirmasi" },
    { id: "ARMADA_DIJADWALKAN", label: "Armada Dijadwalkan" },
    { id: "PERLU_ASSIGN_ARMADA", label: "Perlu Assign Armada" },
    { id: "PERLU_KONFIRMASI_SIAP", label: "Perlu Konfirmasi Siap" },
    { id: "PERLU_RESPON_PERUBAHAN", label: "Perlu Respon Perubahan" },
    { id: "PROSES_MUAT", label: "Proses Muat" },
    { id: "PROSES_BONGKAR", label: "Proses Bongkar" },
    { id: "DOKUMEN_SEDANG_DISIAPKAN", label: "Dokumen Sedang Disiapkan" },
    { id: "PROSES_PENGIRIMAN_DOKUMEN", label: "Proses Pengiriman Dokumen" },
    { id: "DIBATALKAN_SHIPPER", label: "Dibatalkan Shipper" },
    { id: "DIBATALKAN_TRANSPORTER", label: "Dibatalkan Transporter" },
    { id: "DIBATALKAN_SISTEM", label: "Dibatalkan Sistem" },
    { id: "SELESAI", label: "Selesai" },
  ],
};
