export const successResponse = {
  Message: {
    Code: 200,
    Text: "Data transporter berhasil diambil",
  },
  Data: {
    transporters: [
      {
        id: "uuid-transporter-1",
        companyName: "PT Maju Jaya",
        companyLogo: "https://storage.url/logo1.jpg",
        companyEmail: "maju@mail.com",
        picName: "Budi Santoso",
        picPosition: "Manager",
        picPhone: "082112345678",
        companyAddress: "Jalan Sudirman 123, Jakarta Pusat",
        fleetCount: 15,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-01-15T08:30:00Z",
      },
      {
        id: "uuid-transporter-2",
        companyName: "CV Berkah Mandiri",
        companyLogo: "https://storage.url/logo2.jpg",
        companyEmail: "berkah@mail.com",
        picName: "Siti Rahayu",
        picPosition: "Director",
        picPhone: "082298765432",
        companyAddress: "Jalan Thamrin 456, Jakarta Pusat",
        fleetCount: 8,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-02-10T10:15:00Z",
      },
      {
        id: "uuid-transporter-3",
        companyName: "PT Sejahtera Bersama",
        companyLogo: "https://storage.url/logo3.jpg",
        companyEmail: "sejahtera@mail.com",
        picName: "Agus Wijaya",
        picPosition: "Operations Manager",
        picPhone: "082355551111",
        companyAddress: "Jalan Gatot Subroto 789, Jakarta Selatan",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-01-20T14:20:00Z",
      },
      {
        id: "uuid-transporter-4",
        companyName: "CV Bahagia Sentosa",
        companyLogo: "https://storage.url/logo4.jpg",
        companyEmail: "bahagia@mail.com",
        picName: "Dewi Lestari",
        picPosition: "CEO",
        picPhone: "082422223333",
        companyAddress: "Jalan HR Rasuna Said 101, Jakarta Selatan",
        fleetCount: 12,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-03-05T12:45:00Z",
      },
      {
        id: "uuid-transporter-5",
        companyName: "CV Moga Jaya Abadi",
        companyLogo: "https://storage.url/logo5.jpg",
        companyEmail: "contact.shipper@mail.com",
        picName: "Ahmad Maulana",
        picPosition: "Manager",
        picPhone: "082155556666111",
        companyAddress: "Jalan Kedungdoro 101A, Tegalsari, Surabaya",
        fleetCount: 0,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-03-10T09:20:00Z",
      },
      {
        id: "uuid-transporter-6",
        companyName: "PT Karya Utama",
        companyLogo: "https://storage.url/logo6.jpg",
        companyEmail: "karya@mail.com",
        picName: "Joko Susilo",
        picPosition: "Director",
        picPhone: "082544445555123",
        companyAddress: "Jalan Diponegoro 202, Bandung",
        fleetCount: 20,
        isActive: false,
        status: "VERIFICATION_REJECTED",
        createdAt: "2023-02-20T16:30:00Z",
      },
      {
        id: "uuid-transporter-7",
        companyName: "CV Sukses Makmur",
        companyLogo: "https://storage.url/logo7.jpg",
        companyEmail: "sukses@mail.com",
        picName: "Rina Permata",
        picPosition: "Manager",
        picPhone: "082666667777",
        companyAddress: "Jalan Asia Afrika 303, Bandung",
        fleetCount: 5,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-03-15T11:10:00Z",
      },
      {
        id: "uuid-transporter-8",
        companyName: "PT Harapan Baru",
        companyLogo: "https://storage.url/logo8.jpg",
        companyEmail: "harapan@mail.com",
        picName: "Eko Prasetyo",
        picPosition: "CEO",
        picPhone: "082788889999",
        companyAddress: "Jalan Malioboro 404, Yogyakarta",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-01-25T13:50:00Z",
      },
      {
        id: "uuid-transporter-9",
        companyName: "CV Mitra Sejati",
        companyLogo: "https://storage.url/logo9.jpg",
        companyEmail: "mitra@mail.com",
        picName: "Lina Andriani",
        picPosition: "Director",
        picPhone: "082811112222",
        companyAddress: "Jalan Pajajaran 505, Bogor",
        fleetCount: 18,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-04-01T08:15:00Z",
      },
      {
        id: "uuid-transporter-10",
        companyName: "PT Teknologi Maju",
        companyLogo: "https://storage.url/logo10.jpg",
        companyEmail: "teknologi@mail.com",
        picName: "Bambang Hartono",
        picPosition: "Operations Manager",
        picPhone: "08293333444410",
        companyAddress: "Jalan Veteran 606, Malang",
        fleetCount: 7,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-04-10T14:25:00Z",
      },
      {
        id: "uuid-transporter-11",
        companyName: "CV Nusantara Express",
        companyLogo: "https://storage.url/logo11.jpg",
        companyEmail: "nusantara@express.com",
        picName: "Sari Dewanti",
        picPosition: "Manager",
        picPhone: "081234567891",
        companyAddress: "Jalan Merdeka 100, Surabaya",
        fleetCount: 22,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-05-15T10:30:00Z",
      },
      {
        id: "uuid-transporter-12",
        companyName: "PT Global Logistics",
        companyLogo: "https://storage.url/logo12.jpg",
        companyEmail: "global@logistics.co.id",
        picName: "Rahman Wijaya",
        picPosition: "CEO",
        picPhone: "081345678912123",
        companyAddress: "Jalan Kemang 200, Jakarta Selatan",
        fleetCount: 35,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-05-20T14:15:00Z",
      },
      {
        id: "uuid-transporter-13",
        companyName: "CV Berkah Transport",
        companyLogo: "https://storage.url/logo13.jpg",
        companyEmail: "berkah@transport.com",
        picName: "Indira Sari",
        picPosition: "Operations Manager",
        picPhone: "081456789123",
        companyAddress: "Jalan Sudirman 300, Bandung",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-02-28T09:45:00Z",
      },
      {
        id: "uuid-transporter-14",
        companyName: "PT Sentosa Mandiri",
        companyLogo: "https://storage.url/logo14.jpg",
        companyEmail: "sentosa@mandiri.com",
        picName: "Andi Pratama",
        picPosition: "Director",
        picPhone: "081567891234456",
        companyAddress: "Jalan Gatot Subroto 400, Jakarta",
        fleetCount: 28,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-06-01T16:20:00Z",
      },
      {
        id: "uuid-transporter-15",
        companyName: "CV Jaya Abadi",
        companyLogo: "https://storage.url/logo15.jpg",
        companyEmail: "jaya@abadi.com",
        picName: "Sri Mulyani",
        picPosition: "Manager",
        picPhone: "081678912345",
        companyAddress: "Jalan Diponegoro 500, Yogyakarta",
        fleetCount: 12,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-06-10T11:30:00Z",
      },
      {
        id: "uuid-transporter-16",
        companyName: "PT Maju Bersama",
        companyLogo: "https://storage.url/logo16.jpg",
        companyEmail: "maju@bersama.co.id",
        picName: "Dodi Hermawan",
        picPosition: "CEO",
        picPhone: "081789123456789",
        companyAddress: "Jalan Asia Afrika 600, Bandung",
        fleetCount: 0,
        isActive: false,
        status: "VERIFICATION_REJECTED",
        createdAt: "2023-03-20T13:15:00Z",
      },
      {
        id: "uuid-transporter-17",
        companyName: "CV Harmoni Transport",
        companyLogo: "https://storage.url/logo17.jpg",
        companyEmail: "harmoni@transport.com",
        picName: "Lestari Ningrum",
        picPosition: "Operations Manager",
        picPhone: "081891234567",
        companyAddress: "Jalan Veteran 700, Malang",
        fleetCount: 16,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-06-25T08:45:00Z",
      },
      {
        id: "uuid-transporter-18",
        companyName: "PT Sukses Logistik",
        companyLogo: "https://storage.url/logo18.jpg",
        companyEmail: "sukses@logistik.com",
        picName: "Bambang Setiawan",
        picPosition: "Director",
        picPhone: "081912345678901",
        companyAddress: "Jalan Thamrin 800, Jakarta Pusat",
        fleetCount: 45,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-07-05T15:20:00Z",
      },
      {
        id: "uuid-transporter-19",
        companyName: "CV Bahagia Cargo",
        companyLogo: "https://storage.url/logo19.jpg",
        companyEmail: "bahagia@cargo.com",
        picName: "Fitri Handayani",
        picPosition: "Manager",
        picPhone: "082123456789",
        companyAddress: "Jalan Pahlawan 900, Surabaya",
        fleetCount: 8,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-07-15T12:10:00Z",
      },
      {
        id: "uuid-transporter-20",
        companyName: "PT Cahaya Express",
        companyLogo: "https://storage.url/logo20.jpg",
        companyEmail: "cahaya@express.co.id",
        picName: "Agung Prasetyo",
        picPosition: "CEO",
        picPhone: "082234567891234",
        companyAddress: "Jalan Pemuda 1000, Semarang",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-04-15T09:30:00Z",
      },
      {
        id: "uuid-transporter-21",
        companyName: "CV Prima Transport",
        companyLogo: "https://storage.url/logo21.jpg",
        companyEmail: "prima@transport.com",
        picName: "Dewi Kartika",
        picPosition: "Operations Manager",
        picPhone: "082345678912",
        companyAddress: "Jalan Kedungsari 1100, Surabaya",
        fleetCount: 19,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-07-25T14:40:00Z",
      },
      {
        id: "uuid-transporter-22",
        companyName: "PT Makmur Sejahtera",
        companyLogo: "https://storage.url/logo22.jpg",
        companyEmail: "makmur@sejahtera.com",
        picName: "Hendra Gunawan",
        picPosition: "Director",
        picPhone: "082456789123456",
        companyAddress: "Jalan Raya 1200, Bekasi",
        fleetCount: 33,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-08-01T10:15:00Z",
      },
      {
        id: "uuid-transporter-23",
        companyName: "CV Sinar Harapan",
        companyLogo: "https://storage.url/logo23.jpg",
        companyEmail: "sinar@harapan.com",
        picName: "Maya Sari",
        picPosition: "Manager",
        picPhone: "082567891234",
        companyAddress: "Jalan Panglima Sudirman 1300, Medan",
        fleetCount: 14,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-08-10T16:25:00Z",
      },
      {
        id: "uuid-transporter-24",
        companyName: "PT Bintang Timur",
        companyLogo: "https://storage.url/logo24.jpg",
        companyEmail: "bintang@timur.co.id",
        picName: "Rudi Santoso",
        picPosition: "CEO",
        picPhone: "082678912345678",
        companyAddress: "Jalan Jendral Ahmad Yani 1400, Makassar",
        fleetCount: 0,
        isActive: false,
        status: "VERIFICATION_REJECTED",
        createdAt: "2023-05-05T11:50:00Z",
      },
      {
        id: "uuid-transporter-25",
        companyName: "CV Mentari Logistics",
        companyLogo: "https://storage.url/logo25.jpg",
        companyEmail: "mentari@logistics.com",
        picName: "Siti Nurhaliza",
        picPosition: "Operations Manager",
        picPhone: "082789123456",
        companyAddress: "Jalan Cut Nyak Dien 1500, Banda Aceh",
        fleetCount: 21,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-08-20T13:35:00Z",
      },
      {
        id: "uuid-transporter-26",
        companyName: "PT Garuda Transport",
        companyLogo: "https://storage.url/logo26.jpg",
        companyEmail: "garuda@transport.co.id",
        picName: "Eko Widodo",
        picPosition: "Director",
        picPhone: "082891234567891",
        companyAddress: "Jalan Soekarno Hatta 1600, Palembang",
        fleetCount: 27,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-09-01T09:20:00Z",
      },
      {
        id: "uuid-transporter-27",
        companyName: "CV Sejahtera Cargo",
        companyLogo: "https://storage.url/logo27.jpg",
        companyEmail: "sejahtera@cargo.com",
        picName: "Rina Marlina",
        picPosition: "Manager",
        picPhone: "082912345678",
        companyAddress: "Jalan Imam Bonjol 1700, Padang",
        fleetCount: 9,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-09-10T15:45:00Z",
      },
      {
        id: "uuid-transporter-28",
        companyName: "PT Nusa Express",
        companyLogo: "https://storage.url/logo28.jpg",
        companyEmail: "nusa@express.com",
        picName: "Wayan Sudana",
        picPosition: "CEO",
        picPhone: "083123456789123",
        companyAddress: "Jalan Hayam Wuruk 1800, Denpasar",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-06-30T12:55:00Z",
      },
      {
        id: "uuid-transporter-29",
        companyName: "CV Borneo Logistics",
        companyLogo: "https://storage.url/logo29.jpg",
        companyEmail: "borneo@logistics.com",
        picName: "Surya Dinata",
        picPosition: "Operations Manager",
        picPhone: "083234567891",
        companyAddress: "Jalan A. Yani 1900, Balikpapan",
        fleetCount: 17,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-09-25T14:10:00Z",
      },
      {
        id: "uuid-transporter-30",
        companyName: "PT Wijaya Transport",
        companyLogo: "https://storage.url/logo30.jpg",
        companyEmail: "wijaya@transport.co.id",
        picName: "Made Sutrisna",
        picPosition: "Director",
        picPhone: "083345678912345",
        companyAddress: "Jalan Gajah Mada 2000, Mataram",
        fleetCount: 24,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-10-05T10:25:00Z",
      },
      {
        id: "uuid-transporter-31",
        companyName: "CV Persada Cargo",
        companyLogo: "https://storage.url/logo31.jpg",
        companyEmail: "persada@cargo.com",
        picName: "Indah Permatasari",
        picPosition: "Manager",
        picPhone: "083456789123",
        companyAddress: "Jalan Wahid Hasyim 2100, Pekanbaru",
        fleetCount: 11,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-10-15T16:40:00Z",
      },
      {
        id: "uuid-transporter-32",
        companyName: "PT Samudra Express",
        companyLogo: "https://storage.url/logo32.jpg",
        companyEmail: "samudra@express.com",
        picName: "Rizki Ramadhan",
        picPosition: "CEO",
        picPhone: "083567891234567",
        companyAddress: "Jalan Diponegoro 2200, Lampung",
        fleetCount: 0,
        isActive: false,
        status: "VERIFICATION_REJECTED",
        createdAt: "2023-07-20T11:15:00Z",
      },
      {
        id: "uuid-transporter-33",
        companyName: "CV Mandala Transport",
        companyLogo: "https://storage.url/logo33.jpg",
        companyEmail: "mandala@transport.com",
        picName: "Lina Susanti",
        picPosition: "Operations Manager",
        picPhone: "083678912345",
        companyAddress: "Jalan Kartini 2300, Jambi",
        fleetCount: 13,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-10-25T13:50:00Z",
      },
      {
        id: "uuid-transporter-34",
        companyName: "PT Fajar Logistics",
        companyLogo: "https://storage.url/logo34.jpg",
        companyEmail: "fajar@logistics.co.id",
        picName: "Yudi Prakoso",
        picPosition: "Director",
        picPhone: "083789123456789",
        companyAddress: "Jalan Sudirman 2400, Bengkulu",
        fleetCount: 26,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-11-01T09:05:00Z",
      },
      {
        id: "uuid-transporter-35",
        companyName: "CV Elang Express",
        companyLogo: "https://storage.url/logo35.jpg",
        companyEmail: "elang@express.com",
        picName: "Nurul Hidayah",
        picPosition: "Manager",
        picPhone: "083891234567",
        companyAddress: "Jalan Hang Tuah 2500, Palu",
        fleetCount: 7,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-11-10T15:30:00Z",
      },
      {
        id: "uuid-transporter-36",
        companyName: "PT Surya Cargo",
        companyLogo: "https://storage.url/logo36.jpg",
        companyEmail: "surya@cargo.com",
        picName: "Denny Kurniawan",
        picPosition: "CEO",
        picPhone: "083912345678901",
        companyAddress: "Jalan Veteran 2600, Kendari",
        fleetCount: 0,
        isActive: false,
        status: "NON_ACTIVE",
        createdAt: "2023-08-25T12:20:00Z",
      },
      {
        id: "uuid-transporter-37",
        companyName: "CV Bayu Transport",
        companyLogo: "https://storage.url/logo37.jpg",
        companyEmail: "bayu@transport.com",
        picName: "Sari Oktaviani",
        picPosition: "Operations Manager",
        picPhone: "084123456789",
        companyAddress: "Jalan Pangeran Diponegoro 2700, Manado",
        fleetCount: 18,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-11-20T14:45:00Z",
      },
      {
        id: "uuid-transporter-38",
        companyName: "PT Cendana Logistics",
        companyLogo: "https://storage.url/logo38.jpg",
        companyEmail: "cendana@logistics.co.id",
        picName: "Ahmad Fauzi",
        picPosition: "Director",
        picPhone: "084234567891234",
        companyAddress: "Jalan Ahmad Yani 2800, Ambon",
        fleetCount: 31,
        isActive: true,
        status: "ACTIVE",
        createdAt: "2023-12-01T10:35:00Z",
      },
      {
        id: "uuid-transporter-39",
        companyName: "CV Pesona Express",
        companyLogo: "https://storage.url/logo39.jpg",
        companyEmail: "pesona@express.com",
        picName: "Kartika Dewi",
        picPosition: "Manager",
        picPhone: "084345678912",
        companyAddress: "Jalan Merdeka 2900, Jayapura",
        fleetCount: 5,
        isActive: true,
        status: "PENDING_VERIFICATION",
        createdAt: "2023-12-10T16:15:00Z",
      },
      {
        id: "uuid-transporter-40",
        companyName: "PT Mega Transport",
        companyLogo: "https://storage.url/logo40.jpg",
        companyEmail: "mega@transport.com",
        picName: "Budi Santoso",
        picPosition: "CEO",
        picPhone: "084456789123456",
        companyAddress: "Jalan Hasanuddin 3000, Ternate",
        fleetCount: 0,
        isActive: false,
        status: "VERIFICATION_REJECTED",
        createdAt: "2023-09-15T11:25:00Z",
      },
    ],
    pagination: {
      currentPage: 1,
      totalPages: 8,
      totalItems: 40,
      itemsPerPage: 10,
    },
  },
  Type: "GET_TRANSPORTERS_LIST",
};

export const errorResponse = {
  Message: {
    Code: 400,
    Text: "Parameter tidak valid",
  },
  Data: {
    errors: [
      {
        field: "search",
        message: "Pencarian harus minimal 3 karakter",
      },
    ],
  },
  Type: "GET_TRANSPORTERS_LIST_ERROR",
};

// Add additional error responses if needed
export const serverErrorResponse = {
  Message: {
    Code: 500,
    Text: "Internal Server Error",
  },
  Data: {
    errors: [
      {
        field: "general",
        message: "Terjadi kesalahan pada sistem kami",
      },
    ],
  },
  Type: "INTERNAL_SERVER_ERROR",
};

export const unauthorizedResponse = {
  Message: {
    Code: 401,
    Text: "Unauthorized",
  },
  Data: {
    errors: [
      {
        field: "auth",
        message:
          "Akses ditolak. Anda tidak memiliki izin untuk mengakses data ini",
      },
    ],
  },
  Type: "UNAUTHORIZED_ACCESS",
};
